title: "Burning Cost"
description: "Open-source pricing tools for UK insurance teams."
baseurl: ""
url: "https://burningcost.github.io"

author:
  name: "Burning Cost"
  email: "pricing.frontier@gmail.com"

theme: minima

minima:
  skin: classic

header_pages:
  - course.md
  - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

show_excerpts: true

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:year/:month/:day/:title/

github:
  - repo: "https://github.com/burningcost/shap-relativities"

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
